name: tests

on:
  push:
    branches: [ hotfix-0119 ]
  pull_request:
    branches: [ hotfix-0119 ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install Package
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .
      - name: Run Tests
        run: |
          ./scripts/run-python-tests.sh
